name: MLInvestments Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from MLInvestments Organization
      - id: foo
        uses: actions/composite-action-repo01@v1
        with:
          who-to-greet: 'Srinivas Charan Mamidi'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
